language: go
sudo: required
cache: pip
go:
#- 1.7
- tip
install:
- pip install --user mkdocs
- go get github.com/noqcks/gucci
- go get github.com/mitchellh/gox
- go get -d -v ./...
script:
- go test -v ./...
- ./.build.sh
- ./.gen-docs.sh
after_success:
- ./.publish-docs.sh
deploy:
  provider: releases
  api_key:
    secure: KfouJ7pP5hKnTHe3swVQ7Np4bbEcPLVga2P1CUzNQjH0yotm3kpCets6zQG8+ounKWPyxF+Ez+KSG/s1Do+anqw5p5z0nfK3942KrPprXMMdSTw1jIDts5+jDtyslRVqMdFYSKNClVVc8Xpr/cUop0c7qBa3lZExgdXBb3Jp4F7MjPPCRR4WUBn3GINrVookPqujr9cq9pjfd0kqLisltP0ScQG7cW5A1tn4ldzyw9mLlH1h4EXAYwIYUbrjg5f94p4QSFXiZxjIe700y2zsCk9HZn2fBxWbnxv0HwfqpP05eV95VOjdeelSjGU9u67oJJ+HvfELv0xFRegr/b77yQn4Qi08nzUzOWeVeBmSc2Zixm41+oVCcMtpaEN0Gd6bYBSuy1hN1g1x5KrBSMq6i766S+Y7GbmjJv2GQRDIWb0WvJ36mpkPZmUVDWxiodM0Htof4YbpajlmiuLxYsvY5ARq5fF3PVWi4Iy1GYNxp+Ozzqr0fT1FFjwXoXwXLJcgyHxZ8Kn+eXHphu/IRtWWIHgPEzAtOTDdzx6oj+S3+uEbYTpudsGkM/tgj1ruRJ8KU4hAaMSH4R0F2mFiMi4zVWkw+JkM6NTRLr6fuxUolCZpwMS4IbHecsjGY1R3jlVjjvZssj98du84/JY0d7e7BUJTqz3iflgUA7Zmanou3Nc=
  file:
    - crash_darwin_amd64
    - crash_linux_amd64
    - crash_windows_amd64.exe
    - crash_docs.tar.gz
    - sha256sum.txt
  skip_cleanup: true
  on:
    repo: troykinsella/crash
    tags: true
    go: tip
