language: go
sudo: required
cache: pip
go:
- 1.7
- tip
env:
  global:
    secure: mh9hNEyghgwyVBGVDCVDlfHj7e+LonvnMxkv6p12VvDGoG21lgqlMtOhEb+4HVopVfBlyNPSt/rntBcA461vx6XRlmgvOnbQVGHGRFIV/MYM2+rNMyk0ecGZJ1IL4M6Dv/81vt7NRJ7Rf2MDyjzeFR/NgptNkdsM3Pc3zYxN51KmYRLbOuJYNZYin3+YDKXEJvnZzc2SYQUU5B+3TROUCfWr/UoxI/3xDTXNikLaeEJlgrebkhxxn4QAJia9jICSnuIx0kEq6YN4ApXMHTbP54j1qbuzBnQ8x9bxCB1eaOlf+UCi/0uK8Ias4TQHSHiDay2s4+w/uVg8+ebQIgzBqm8N2qgsqD/hspqhZXA+psDsYlJP4jhhluSIgiHHKu10XOnDMwRV6ji0BM3MYS8KNeLnzXCIlOQCG8zBrx9q7vcYSviqBUKGE6hlBBwwhpUZmx3odcBwyR14dl7p1HZFKH8eLrMXAahdKbRKdOZ54QeRlzCVUKTA6URF8JZT9Zm3K5/K1SwQipFSXtEIHNb33WKAWLP7yXS2ZbsreWGO0SEbeZjdfzcGYtmAAqIebmTdQkg9CFfVOi/R8QOuKbTeWm+KhHFeVQY+/TJBvSM1uxXiAaTtTMnECTXXkA8rV72TP0Pjz72kzNfO1qaP7ERfRpt8Na/BJLW7J+7e3U4MWlE=
install:
- go get github.com/mitchellh/gox
- go get -d -v ./...
- gox -arch="amd64" -os="darwin linux windows" -output="crash_{{.OS}}_{{.Arch}}" github.com/troykinsella/crash/cmd
- sha256sum crash_* > sha256sum.txt
deploy:
  provider: releases
  api_key:
    secure: KfouJ7pP5hKnTHe3swVQ7Np4bbEcPLVga2P1CUzNQjH0yotm3kpCets6zQG8+ounKWPyxF+Ez+KSG/s1Do+anqw5p5z0nfK3942KrPprXMMdSTw1jIDts5+jDtyslRVqMdFYSKNClVVc8Xpr/cUop0c7qBa3lZExgdXBb3Jp4F7MjPPCRR4WUBn3GINrVookPqujr9cq9pjfd0kqLisltP0ScQG7cW5A1tn4ldzyw9mLlH1h4EXAYwIYUbrjg5f94p4QSFXiZxjIe700y2zsCk9HZn2fBxWbnxv0HwfqpP05eV95VOjdeelSjGU9u67oJJ+HvfELv0xFRegr/b77yQn4Qi08nzUzOWeVeBmSc2Zixm41+oVCcMtpaEN0Gd6bYBSuy1hN1g1x5KrBSMq6i766S+Y7GbmjJv2GQRDIWb0WvJ36mpkPZmUVDWxiodM0Htof4YbpajlmiuLxYsvY5ARq5fF3PVWi4Iy1GYNxp+Ozzqr0fT1FFjwXoXwXLJcgyHxZ8Kn+eXHphu/IRtWWIHgPEzAtOTDdzx6oj+S3+uEbYTpudsGkM/tgj1ruRJ8KU4hAaMSH4R0F2mFiMi4zVWkw+JkM6NTRLr6fuxUolCZpwMS4IbHecsjGY1R3jlVjjvZssj98du84/JY0d7e7BUJTqz3iflgUA7Zmanou3Nc=
  file:
    - crash_darwin_amd64
    - crash_linux_amd64
    - crash_windows_amd64.exe
    - sha256sum.txt
  skip_cleanup: true
  on:
    repo: troykinsella/crash
    tags: true
after_success:
- pip install --user mkdocs
- mkdocs build
- ./.publish-docs.sh
