site_name: Crash Documentation
repo_url: https://github.com/troykinsella/crash
site_author: Troy Kinsella
site_favicon: favicon.ico
copyright: Copyright © 2016 Troy Kinsella
pages:
- index.md
- Test Plans: test_plans.md
- Action Reference:
  - http: actions/http.md
  - shell: actions/shell.md
- contributing.md
theme: readthedocs
